title: "Your Portfolio"
email: "your.email@example.com"
description: "A brief description of your site."
baseurl: ""
url: https://unspecifyed.github.io/
theme: "minimal-mistakes-jekyll"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Your Name"
  avatar: "/assets/images/profile.jpg"
  links:
    - label: "GitHub"
      url: "https://github.com/yourusername"
    - label: "LinkedIn"
      url: "https://linkedin.com/in/yourusername"
