title: "Francis Cottrell-Eshaghi's Portfolio"
email: "francis.cottrell-eshaghi@snhu.edu"
description: "Portfolio and resume for Francis Cottrell-Eshaghi."
baseurl: ""
url: "https://unspecifyed.github.io"
theme: "minimal-mistakes-jekyll"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional social links
author: "Francis Cottrell-Eshaghi"
  name: "Francis Cottrell-Eshaghi"
  avatar: "/assets/images/profile.jpg"
  links:
    - label: "GitHub"
      url: "https://github.com/unspecifyed"
    - label: "LinkedIn"
      url: https://www.linkedin.com/in/francis-cottrell-eshaghi-8a8572249/ 
